include:
  - n8n/docker-compose-n8n.yml
  - ollama/docker-compose-ollama.yml
  - qdrant/docker-compose-qdrant.yml
  - open-webui/docker-compose-open-webui.yml
  - selenium/docker-compose-selenium.yml
  - flaresolverr/docker-compose-flaresolverr.yml

networks:
  demo: